import { table, autoGeneratedHashKey, rangeKey, attribute } from '@aws/dynamodb-data-mapper-annotations';

@table('bloggs')
export class Blogg {
    @autoGeneratedHashKey()
    id: string;
    
    @rangeKey({defaultProvider: () => new Date()})
    createdAt: Date;

    @attribute()
    username: string;

    @attribute()
    body: string;
}
